### ISSUE TITLE
How to get the output for memcached_endpoint

### ISSUE THREAD

**Issue by yun14u** [clouddrove/terraform-aws-elasticache#10]
While using your module of memcached, I included the following code block for output

**output "endpoint" {
    value = module.memcached.memcached_endpoint
}**

But while performing `terraform plan`, it complained that

_On   blahblah.tf  line 207, in output "endpoint":
207:   value = module.memcached.memcached_endpoint

This object does not have an attribute named "memcached_endpoint"._

**Comment by sohanyadav** [comment]
@yun14u  working fine for me, you need to add the following code in https://github.com/clouddrove/terraform-aws-elasticache/blob/master/_example/memcached/outputs.tf


**output "endpoint" {
value = module.memcached.memcached_endpoint
}**
