### ISSUE TITLE
Format and syntax errors on example

### ISSUE THREAD

**Issue by mgleria-govplus** [clouddrove/terraform-aws-elasticache#51]
Hey, I've tried to use the "Redis" example from the README, and I found the following issues:

1. missing the closing quote in the source attribute
2. missing the closing "}" at the end of the module
3. indentation issues

After tweaking some attribute values and running `terraform plan`, I got these errors: 

```
│ Error: Missing required argument
│ 
│   on redis.tf line 1, in module "redis":
│    1: module "redis" {
│ 
│ The argument "route53_zone_id" is required, but no definition was found.
╵
╷
│ Error: Unsupported argument
│ 
│   on redis.tf line 14, in module "redis":
│   14:     replication_enabled         = true
│ 
│ An argument named "replication_enabled" is not expected here.
```

Thanks anyway for sharing, and please let me know if I'm missing something.

**Comment by theprashantyadav** [comment]
@mgleria-govplus Hi I ad both argument in README so now you use latest code 
thanks
