### ISSUE TITLE
[REQUEST] add `user_group_ids` to `aws_elasticache_replication_group`

### ISSUE THREAD

**Issue by jserpapinto** [clouddrove/terraform-aws-elasticache#62]
Hey guys,

Is it possible to add a `user_group_ids` to the `aws_elasticache_replication_group`?

I can make the pull request if needed, just trying to check if is something you think is ok to add.

**Comment by theprashantyadav** [comment]
Hello @jserpapinto 
Added argument of user_group_ids see in PR https://github.com/clouddrove/terraform-aws-elasticache/pull/65
