### ISSUE TITLE
[REQUEST] add `final_snapshot_identifier` argument

### ISSUE THREAD

**Issue by nawarajshahi** [clouddrove/terraform-aws-elasticache#66]
Hello
Can we add `final_snapshot_identifier` to the `aws_elasticache_replication_group` ? 

Currently, this feature prevents from enabling taking final snapshot. Happy to open PR if you'd like. Thanks!

**Comment by themaniskshah** [comment]
Thanks for the suggestion @nawarajshahi . Yes, please, if possible create a PR.
